### PR TITLE
A few edits to the PyNam project

### PR DESCRIPTION
**Pull request by izakotim**
Nothing major, getting warmed up.

### CODE REVIEW

**Comment by Namibnat** [comment]
Great!

**Comment by izakotim** [comment]
Might need some help though..after cloning the poject, i couldnt find the templates or css or anything.. realised i didnt set up my server locally etc..not sure how that works, but would that be an issue seeing that those are files too?

**Comment by Namibnat** [comment]
The css and template files were just not added yet.

**Comment by izakotim** [comment]
oh okay.

**Pull request merged**
